# Generated by Django 6.0.4 on 2026-04-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_state_microservice_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userserviceaccount',
            name='session_cookies',
            field=models.TextField(blank=True, null=True),
        ),
    ]
