# Generated by Django 6.0.4 on 2026-04-20 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ui_theme',
            field=models.CharField(choices=[('default', 'Standard Blue'), ('premium', 'Premium Gold'), ('platinum', 'Platinum Sleek'), ('emerald', 'Emerald Executive')], default='default', max_length=20),
        ),
    ]
