# Generated by Django 6.0.4 on 2026-04-20 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_profile_ui_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='custom_hue',
            field=models.IntegerField(default=335),
        ),
    ]
