# Generated by Django 6.0.4 on 2026-04-20 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_profile_custom_hue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='ui_theme',
        ),
    ]
